package kr.hhplus.be.server.unit.domain.reservation.model;

import kr.hhplus.be.server.domain.concert.model.seat.Seat;
import kr.hhplus.be.server.domain.reservation.model.Reservation;
import kr.hhplus.be.server.domain.reservation.model.ReservationExpirationPolicy;
import kr.hhplus.be.server.domain.reservation.model.ReservationStatus;
import kr.hhplus.be.server.domain.user.model.User;
import kr.hhplus.be.server.unit.BaseUnitTest;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneId;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;

public class ReservationTest extends BaseUnitTest {
    @Test
    @DisplayName("Reservation.create creates a temporary hold with fixed expiration")
    void testCreateReservation() {
        User user = new User();
        Seat seat = new Seat();
        Instant fixedInstant = fixedNow().atZone(ZoneId.of("UTC")).toInstant();
        Clock fixedClock = Clock.fixed(fixedInstant, ZoneId.of("UTC"));
        ReservationExpirationPolicy expirationPolicy = now -> fixedNow().plusMinutes(5);

        Reservation reservation = Reservation.create(user, seat, fixedClock, expirationPolicy);

        // The id is generated by JPA when the entity is persisted.
        assertNull(reservation.getId());
        assertEquals(user, reservation.getUser());
        assertEquals(seat, reservation.getSeat());
        assertEquals(ReservationStatus.TEMP_HOLD, reservation.getStatus());
        assertEquals(fixedNow().plusMinutes(5), reservation.getTempHoldExpiresAt());
        assertNull(reservation.getConfirmedAt());
        assertFalse(reservation.isDeleted());
    }
}
