package kr.hhplus.be.server.unit.domain.concert.model;

import kr.hhplus.be.server.concert.domain.model.Concert;
import kr.hhplus.be.server.concert.domain.model.ConcertDate;
import kr.hhplus.be.server.unit.BaseUnitTest;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;

public class ConcertDateTest extends BaseUnitTest {
    @Test
    @DisplayName("ConcertDate.create initializes required fields")
    void testConcertDateCreate() {
        Concert concert = Concert.create("Test Concert", "Test Description");
        LocalDate eventDate = LocalDate.of(2025, 12, 25);

        ConcertDate concertDate = ConcertDate.create(concert, eventDate);

        // The id is generated by JPA when the entity is persisted.
        assertNull(concertDate.getId());
        assertEquals(concert, concertDate.getConcert());
        assertEquals(eventDate, concertDate.getEventDate());
        assertFalse(concertDate.isDeleted());
        assertNull(concertDate.getCreatedAt());
        assertNull(concertDate.getUpdatedAt());
    }
}
