package kr.hhplus.be.server.unit.domain.payment.model;

import kr.hhplus.be.server.domain.payment.model.Payment;
import kr.hhplus.be.server.domain.payment.model.PaymentMethod;
import kr.hhplus.be.server.domain.payment.model.PaymentStatus;
import kr.hhplus.be.server.domain.reservation.model.Reservation;
import kr.hhplus.be.server.unit.BaseUnitTest;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

public class PaymentTest extends BaseUnitTest {
    @Test
    @DisplayName("createPending creates a pending payment")
    void createPending_shouldCreatePendingPayment() {
        Reservation reservation = Reservation.builder()
                .id(fixedUUID())
                .build();
        int amount = 40000;

        Payment payment = Payment.createPending(reservation, amount, PaymentMethod.CARD);

        // The id is generated by JPA when the entity is persisted.
        assertNull(payment.getId());
        assertEquals(reservation, payment.getReservation());
        assertEquals(amount, payment.getAmount());
        assertEquals(PaymentMethod.CARD, payment.getMethod());
        assertEquals(PaymentStatus.PENDING, payment.getStatus());
        assertNull(payment.getPaidAt());
        assertFalse(payment.isDeleted());
        assertNull(payment.getCreatedAt());
        assertNull(payment.getUpdatedAt());
    }

    @Test
    @DisplayName("Builder sets all payment fields")
    void builder_shouldSetAllFieldsCorrectly() {
        Reservation reservation = Reservation.builder()
                .id(fixedUUID())
                .build();

        Payment payment = Payment.builder()
                .id(fixedUUID())
                .reservation(reservation)
                .amount(55000)
                .method(PaymentMethod.CARD)
                .status(PaymentStatus.PAID)
                .paidAt(fixedNow())
                .deleted(false)
                .build();

        assertEquals(fixedUUID(), payment.getId());
        assertEquals(reservation, payment.getReservation());
        assertEquals(55000, payment.getAmount());
        assertEquals(PaymentMethod.CARD, payment.getMethod());
        assertEquals(PaymentStatus.PAID, payment.getStatus());
        assertNotNull(payment.getPaidAt());
        assertFalse(payment.isDeleted());
        assertNull(payment.getCreatedAt());
        assertNull(payment.getUpdatedAt());
    }
}
